// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "election/internal/logic/account"
	_ "election/internal/logic/candidate"
	_ "election/internal/logic/election"
	_ "election/internal/logic/middleware"
)
