// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ElectionConfigCandidates is the golang structure of table election_config_candidates for DAO operations like Where/Data.
type ElectionConfigCandidates struct {
	g.Meta      `orm:"table:election_config_candidates, do:true"`
	Id          interface{} //
	CandidateId interface{} //
	ElectionId  interface{} //
	VoteCount   interface{} //
}
