// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Elections is the golang structure of table elections for DAO operations like Where/Data.
type Elections struct {
	g.Meta       `orm:"table:elections, do:true"`
	Id           interface{} //
	Title        interface{} // 选举标题
	Introduction interface{} //
	Status       interface{} // 状态 0 - 未开始 1 - 进行中 2 - 已结束
	Starttime    *gtime.Time //
	Endtime      *gtime.Time //
}
