// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"election/internal/model"
)

type (
	ICandidate interface {
		Create(ctx context.Context, in model.CandidateCreateInput) (err error)
		Update(ctx context.Context, in model.CandidateUpdateInput) (err error)
		ChangeStatus(ctx context.Context, in model.CandidateChangeStatuInput) (err error)
		Get(ctx context.Context, in model.CandidateGetInput) (*model.CandidateGetOut, error)
	}
)

var (
	localCandidate ICandidate
)

func Candidate() ICandidate {
	if localCandidate == nil {
		panic("implement not found for interface ICandidate, forgot register?")
	}
	return localCandidate
}

func RegisterCandidate(i ICandidate) {
	localCandidate = i
}
