// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	response "election/internal/lib"
	"election/internal/model"
)

type (
	IElection interface {
		Create(ctx context.Context, in model.ElectionCreateInput) *response.ResultRes
	}
)

var (
	localElection IElection
)

func Election() IElection {
	if localElection == nil {
		panic("implement not found for interface IElection, forgot register?")
	}
	return localElection
}

func RegisterElection(i IElection) {
	localElection = i
}
