// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"election/internal/model"
)

type (
	IUser interface {
		GetElection(ctx context.Context, in model.UserElectionGetInput) (*model.UserElectionGetOut, error)
		Vote(ctx context.Context, in model.UserVoteInput) (err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
