// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"election/internal/dao/internal"
)

// internalCandidatesDao is internal type for wrapping internal DAO implements.
type internalCandidatesDao = *internal.CandidatesDao

// candidatesDao is the data access object for table candidates.
// You can define custom methods on it to extend its functionality as you wish.
type candidatesDao struct {
	internalCandidatesDao
}

var (
	// Candidates is globally public accessible object for table candidates operations.
	Candidates = candidatesDao{
		internal.NewCandidatesDao(),
	}
)

// Fill with you ideas below.
