// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"election/internal/dao/internal"
)

// internalElectionsDao is internal type for wrapping internal DAO implements.
type internalElectionsDao = *internal.ElectionsDao

// electionsDao is the data access object for table elections.
// You can define custom methods on it to extend its functionality as you wish.
type electionsDao struct {
	internalElectionsDao
}

var (
	// Elections is globally public accessible object for table elections operations.
	Elections = electionsDao{
		internal.NewElectionsDao(),
	}
)

// Fill with you ideas below.
