// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"election/internal/dao/internal"
)

// internalElectionUserDetailsDao is internal type for wrapping internal DAO implements.
type internalElectionUserDetailsDao = *internal.ElectionUserDetailsDao

// electionUserDetailsDao is the data access object for table election_user_details.
// You can define custom methods on it to extend its functionality as you wish.
type electionUserDetailsDao struct {
	internalElectionUserDetailsDao
}

var (
	// ElectionUserDetails is globally public accessible object for table election_user_details operations.
	ElectionUserDetails = electionUserDetailsDao{
		internal.NewElectionUserDetailsDao(),
	}
)

// Fill with you ideas below.
