// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Candidates is the golang structure for table candidates.
type Candidates struct {
	Id           int         `json:"id"           description:""`
	Name         string      `json:"name"         description:"候选人名称"`
	Introduction string      `json:"introduction" description:"候选人简介"`
	Image        string      `json:"image"        description:"候选人简介"`
	Status       int         `json:"status"       description:"候选人状态 1 - 可用 0 - 不可用"`
	Createtime   *gtime.Time `json:"createtime"   description:"创建时间"`
	Updatetime   *gtime.Time `json:"updatetime"   description:"更新时间"`
}
