// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ElectionUserDetails is the golang structure for table election_user_details.
type ElectionUserDetails struct {
	Id          int         `json:"id"          description:""`
	ElectionId  int         `json:"electionId"  description:""`
	CandidateId int         `json:"candidateId" description:""`
	IdCard      string      `json:"idCard"      description:""`
	Email       string      `json:"email"       description:""`
	Createtime  *gtime.Time `json:"createtime"  description:""`
}
