// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ElectionConfigCandidates is the golang structure for table election_config_candidates.
type ElectionConfigCandidates struct {
	Id          int `json:"id"          description:""`
	CandidateId int `json:"candidateId" description:""`
	ElectionId  int `json:"electionId"  description:""`
	VoteCount   int `json:"voteCount"   description:""`
	CandidateInfo *Candidates `orm:"with:id=CandidateId"`
}
