// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (

	"github.com/gogf/gf/v2/os/gtime"
)

// Elections is the golang structure for table elections.
type Elections struct {
	Id           int         `json:"id"           description:""`
	Title        string      `json:"title"        description:"选举标题"`
	Introduction string      `json:"introduction" description:""`
	Status       int         `json:"status"       description:"状态 0 - 未开始 1 - 进行中 2 - 已结束"`
	Starttime    *gtime.Time `json:"starttime"    description:""`
	Endtime      *gtime.Time `json:"endtime"      description:""`
	Candidates []*ElectionConfigCandidates `orm:"with:electionId=id"`
}
